### ISSUE TITLE
Add license to repo

### ISSUE THREAD

**Issue by goneall** [mil-oss/spdx-xsd#2]
Suggest adding a license to the repo.

SPDX uses [CC-BY-3.0](https://spdx.org/licenses/CC-BY-ND-3.0.html) for documentation and [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html) for code.

I can propose a PR for the license if you would like.

**Comment by Neutron** [comment]
OK - a PR would be helpful

**Comment by Neutron** [comment]
Merged - Thanks.
