### ISSUE TITLE
Issue mapping type names to specification for classes

### ISSUE THREAD

**Issue by goneall** [mil-oss/spdx-xsd#3]
When generating the JAXB Java class files, the type names are used as the name of the Java classes.  These Java Class names are then used for the RDF class name.  The XSD type names all have "Type" appended to it.

We could change the name of the types in the XSD file to resolve this.

It may also be possible to somehow map the names in the tooling which would require some investigation.

**Comment by Neutron** [comment]
The use of the "Type" and "SimpleType" modifier is required by NIEM.  It is very useful for configuration management and to identify of XML nodes.  

For JAXB the names, and most other things such as recursion can be controlled using XML Schema inline annotations.  (https://stackoverflow.com/questions/4793637/jaxb-how-to-change-xjc-generated-classes-names-when-attr-type-is-specified-in-x) This would be appropriate in a JAXB specific implementation XML Schema.

**Comment by goneall** [comment]
@Neutron I take it the following will not validate due to the names being changed (SpdxDocumentType -> SpdxDocument):

```
<SpdxDocument>
  <Document>
    <specVersion>SPDX-2.0</specVersion>
    <creationInfo>
```

Let me know if we need to retain the "Type" when generating XML to be schema compliant.

If we need to retain the type, we will have an inconsistency in naming between the XML and other formats.  This is OK IMHO as long as I can figure out how to use the annotations to easily convert - thanks for the pointers on that BTW.

**Comment by Neutron** [comment]
These will work if we use lower camel case for element names.  The Type appended names are for XML Schema Type definitions only - so they don't show up anywhere in XML Instances.  The XML Elements are the only names used in the instances.    I can help you create an Extension Schema that has the JAXB inline annotations - once you figure them out - but these don't go in the Reference Schema.  Basically - its bad practice to design the core XSD based on any particular implementation - so while I am indifferent on lower camel case - the Java naming convention is not a valid reason to do it.

**Comment by goneall** [comment]
@Neutron After looking at the referenced stackoverflow article above, I created a JAXB binding file rather than a separate schema.  I took this approach so that I would not have to maintain 2 copies of essentially the same data - I can generate the java class files directly from the canonical schema.

You can see the results at https://github.com/goneall/spdx-xsd/tree/master/java

I noticed a few other details on the generated code I would like to change, but I think they are minor issues which we can change in a future release.

If this approach looks OK to you, we can close this issue.

**Comment by Neutron** [comment]
OK .. there is a brief in the docs folder that explains the NIEM methodology.  It doesn't allow lower camel case.

Implementation level variable names can be specified in a variety of ways - to include annotations in an extension schema,  so it is not a consideration for XML naming.

I created a branch for Java efforts.  Thete can be an extension schema with Java annotations.

⁣Neutron​

**Comment by Neutron** [comment]
This is a JAXB problem that is best solved using JAXB.
